# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    branches:
      - main

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: flutter-actions/setup-flutter@v4
      - name: Install dependencies
        run: dart pub get
      - name: Publish Dry Run
        run: dart pub publish --dry-run
#      - uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    #   working-directory: path/to/package/within/repository